on: ["push"]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Deploy static site
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy static site
        uses: rhussmann/static-site-deploy-action@main
        id: deploy
        with:
          wireguard-private-key: ${{ secrets.CTX_WIREGUARD_PRIVATE_KEY }}
          wireguard-server-public-key: ${{ secrets.CTX_WIREGUARD_SERVER_PUBLIC_KEY }}
          wireguard-server-endpoint: ${{ secrets.CTX_WIREGUARD_SERVER_ENDPOINT }}
          ssh-key: ${{ secrets.CTX_SERVER_DEPLOY_SECRET }}
          domain-name: campcedarstreet.com
          short-name: camp_cedar_street
          kong-host: 192.168.11.103
          kong-port: 8001
          ssh-host: 192.168.11.103
          ssh-user: rhussmann
          deploy-assets: ./*
          kong-nginx-service-name: local_nginx
